theme = "showfolio"
languageCode = "en-us"
baseurl = "https://robcmorris.com"
title = "robcmorris.com"


[params]
  name = "Rob Morris"
  description = "Modern portfolio theme for your Hugo site."
  author = "Rob Morris"
  authorEmail = "me@robcmorris.com"
  authorImage = "/photo.png"
  autoDarkMode = false

  copyright = "Copyright © 2022 - Rob Morris · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Rob Morris"
  tagline = "CompTIA Secure Infrastructure Specialist"
  description = "Sometimes I fix things. I mostly blame end-users."
  contact = "https://twitter.com/robcmo"

# [params.homepage.codepen]
#  username = "apvarun"
#  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Security","Networking","Virtualization","Hardware Configuration","Server Administration","Micosoft 365 Admin","Active Directory","Wireless Administration","Windows OS","Linux OS","Mac OS","Android/iOS","Remote Access","Cloud Networking","Cryptography","Backup and Recovery"]

[[params.homepage.resume.work]]
  name = "Total Business Systems"
  role = "Systems Analyst II"
  duration = "Feb 22 - Present"

[[params.homepage.resume.work]]
  name = "TeamLogic IT"
  role = "Systems Analyst II"
  duration = "Feb 19 - Feb 22"

[[params.homepage.resume.work]]
  name = "Transcom"
  role = "Remote Help Desk Analyst"
  duration = "Jul 16 - Dec 18"

[[params.homepage.resume.work]]
  name = "Conduent"
  role = "Remote Help Desk Analyst"
  duration = "Sep 13 - Jun 16"

[[params.homepage.resume.work]]
  name = "Sykes Enterprises, Inc"
  role = "Learning Developer"
  duration = "Jun 10 - Aug 13"

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  twitter = "https://twitter.com/robcmo"
  linkedin = "https://linkedin.com/in/robcmo"
  github = "https://github.com/robcmorris"
  reddit = "https://reddit.com/robcmo"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
